stages:
  - test

.test:
  image: python:$PYTHON_VERSION
  stage: test
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.7", "3.8", "3.9", "3.10"]
  script:
    - python -m pip install .
    - python -m pip install pytest
    - python -m pip install toml
    - python -m pytest -v -s

build-linux:
  extends: .test
  tags:
    - linux
